
[functions.ml-job]
enabled = true
verify_jwt = true
import_map = "./functions/ml-job/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ml-job/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ml-job/*.html" ]

[functions.proxy-infosimples]
enabled = true
verify_jwt = true
import_map = "./functions/proxy-infosimples/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/proxy-infosimples/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/proxy-infosimples/*.html" ]
